### PR TITLE
Initial values

### PR DESCRIPTION
**Pull request by gregtatum**
Here's some initial code for our discussions in issue #7. I'd like to get some tests in place for this too. This feels a lot nicer when I'm playing with some of my glam examples using it.

### CODE REVIEW

**Comment by mattdesl** [comment]
Sorry, I have a pretty busy week. Will try to review this weekend. :+1: Thanks man!

**Comment by gregtatum** [comment]
No worries! I'm not in any hurry.

**Comment by mattdesl** [comment]
What do you think of `copyInto` instead of `applyTo`?

**Comment by mattdesl** [comment]
Also just reviewing now. Made a few changes:
- changed to `copyInto`, seems a bit clearer ? 
- Right now it just always applies phi/theta for consistency, so that things aren't only getting computed based on user options
- Fixed some problems with `subtract` and using a temp vec3 for it
- `controls.distance` isn't clamped to epsilon any more (to respect user settings), but we still use that when applying phi/theta
- `distanceBounds` defaults to `[0, Infinity]` now, I think it might be a more sane default
- I added a `slice` to target as well, like you did with position

Updated both demos, and made the ThreeJS centred on origin like a StreetView experience. Feels really clean now! :tada:

Thanks man! I'm going to merge and clean up some readme stuff, and publish a major bump.

**Comment by gregtatum** [comment]
Sweet! `.copyInto` works for me, I'm not too opinionated on it. Excited to get this thing going 🎉

**Pull request merged**
